- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install list of packages
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3
      - python3-pip
      - python-setuptools
  - name: Get the  APT key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add the APT repo 
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - name: Install docker using APT
    apt:
     update_cache: true
     name: docker-ce
     state: latest
  - name: Start Docker 
    service:
      name: docker
      state: started
  - name: Install pip3 package for docker 
    pip:
      name: docker
      executable: pip3
  - name: Add the user to docker group
    user: 
      name: d_walker0357
      groups: docker
      append: yes
  - name: restart shell so the user has permissions to use  docker commands
    meta: reset_connection
